src/AdmInflux/Models/ServerViewModel.cs
using System.Collections.Generic;

namespace AdmInflux.Models
{
    public class ServerViewModel
    {
        public string Name { get; set; }
        public List<DatabaseViewModel> Databases { get; set; }
    }
}

src/AdmInflux/Controllers/DatabasesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using AdmInflux.Client;
using AdmInflux.Client.Models;
using AdmInflux.Models;
using Microsoft.AspNetCore.Mvc;

namespace AdmInflux.Controllers
{
    [Route("servers/{server}/databases")]
    public class DatabasesController : Controller
    {
        private readonly InfluxClient _client;

        public DatabasesController(InfluxClient client)
        {
            _client = client;
        }

        [HttpGet("{database}")]
        public async Task<IActionResult> Get(string server, string database)
        {
            var series = await _client.Series.Cardinality(server, database);

            series.Select(s => new MeasurementSeriesViewModel {Measurement = s.Name, Count = s.Count});

            var (measurements, retentionPolicies) = await Tasks.Multi(
                _client.Series.Cardinality(server, database),
                _client.RetentionPolicies.List(server, database)
            ).ConfigureAwait(false);

            var vm = new DatabaseViewModel
            {
                Server = server,
                Name = database,
                Measurements = measurements?.Select(s => new MeasurementSeriesViewModel {Measurement = s.Name, Count = s.Count}).ToArray() ??
                               Array.Empty<MeasurementSeriesViewModel>(),
                RetentionPolicies = retentionPolicies ?? Array.Empty<RetentionPolicy>()
            };
            return View(vm);
        }
    }
}

src/AdmInflux/Controllers/ServersController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using AdmInflux.Client;
using AdmInflux.Client.Models;
using AdmInflux.Models;
using Microsoft.AspNetCore.Mvc;

namespace AdmInflux.Controllers
{
    [Route("servers")]
    public class ServersController : Controller
    {
        private readonly InfluxClient _client;

        public ServersController(InfluxClient client)
        {
            _client = client;
        }

        [HttpGet("{server}")]
        public async Task<IActionResult> Get(string server)
        {
            var databases = await _client.Databases.List(server);
            var dvms = databases.Select(d => new DatabaseViewModel
            {
                Server = server,
                Name = d.Name
            }).ToList();
            
            await Task.WhenAll(dvms.Select(d => Load(server, d)));
            
            var vm = new ServerViewModel
            {
                Name = server,
                Databases = dvms
            };
            return View(vm);
        }

        private async Task Load(string server, DatabaseViewModel database)
        {
            database.SeriesCardinality =
                (await _client.Series.Cardinality(server, database.Name)) ?? Array.Empty<Cardinality>();
        }
    }
}

src/AdmInflux/Views/Servers/Get.cshtml
@model AdmInflux.Models.ServerViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<div class="row">
    <div class="col-12">
        <h1>Databases:</h1>
    </div>
</div>

<div class="row">
    <div class="col-12">
        @foreach (var database in Model.Databases)
        {
            <div class="card">
                <div class="card-header">
                    <h3>
                        <a class="text" asp-controller="Databases" asp-action="Get" asp-route-server="@Model.Name" asp-route-database="@database.Name">@database.Name</a>
                    </h3>
                </div>
                <div class="card-body">
                    @database.SeriesCardinality.Count measurements with @database.SeriesCardinality.Sum(c => c.Count) series
                </div>
            </div>
        }
    </div>
</div>
