src/AdmInflux/Models/MeasurementViewModel.cs
using System.Collections.Generic;
using AdmInflux.Client.Models;

namespace AdmInflux.Models
{
    public class MeasurementViewModel
    {
        public string Server { get; set; }
        public string Database { get; set; }
        public string Name { get; set; }
        public List<Series> Series { get; set; }
    }

    public class MeasurementSeriesViewModel
    {
        public string Measurement { get; set; }
        public int Count { get; set; }
    }
}

src/AdmInflux/Controllers/MeasurementsController.cs
using System.Threading.Tasks;
using AdmInflux.Client;
using AdmInflux.Models;
using Microsoft.AspNetCore.Mvc;

namespace AdmInflux.Controllers
{
    [Route("databases")]
    public class MeasurementsController : Controller
    {
        private readonly InfluxClient _client;

        public MeasurementsController(InfluxClient client)
        {
            _client = client;
        }

        [HttpGet("{server}/{database}/{measurement}")]
        public async Task<IActionResult> Get(string server, string database, string measurement)
        {
            var series = await _client.Series.List(server, database, measurement).ConfigureAwait(false);
            var vm = new MeasurementViewModel {Name = measurement, Series = series};
            return View(vm);
        }
    }
}

src/AdmInflux/Views/Measurements/Get.cshtml
@model AdmInflux.Models.MeasurementViewModel

@{
    ViewBag.Title = $"Measurement: {Model.Name}";
}

<ul>
@foreach (var series in Model.Series)
{
    <li><a asp-controller="Measurements" asp-action="Get" asp-route-database="@Model.Name" asp-route-measurement="@series.Key">@series.Key</a></li>
}
</ul>