src/AdmInflux/Controllers/DatabasesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using AdmInflux.Client;
using AdmInflux.Client.Models;
using AdmInflux.Models;
using Microsoft.AspNetCore.Mvc;

namespace AdmInflux.Controllers
{
    [Route("servers/{server}/databases")]
    public class DatabasesController : Controller
    {
        private readonly InfluxClient _client;

        public DatabasesController(InfluxClient client)
        {
            _client = client;
        }

        [HttpGet("{database}")]
        public async Task<IActionResult> Get(string server, string database)
        {
            var series = await _client.Series.Cardinality(server, database);

            series.Select(s => new MeasurementSeriesViewModel {Measurement = s.Name, Count = s.Count});

            var (measurements, retentionPolicies) = await Tasks.Multi(
                _client.Series.Cardinality(server, database),
                _client.RetentionPolicies.List(server, database)
            ).ConfigureAwait(false);

            var vm = new DatabaseViewModel
            {
                Server = server,
                Name = database,
                Measurements = measurements?.Select(s => new MeasurementSeriesViewModel {Measurement = s.Name, Count = s.Count}).ToArray() ??
                               Array.Empty<MeasurementSeriesViewModel>(),
                RetentionPolicies = retentionPolicies ?? Array.Empty<RetentionPolicy>()
            };
            return View(vm);
        }
    }
}

src/AdmInflux/Controllers/RetentionPolicyController.cs
using System;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using AdmInflux.Client;
using AdmInflux.Client.Models;
using AdmInflux.Models;
using Microsoft.AspNetCore.Mvc;

namespace AdmInflux.Controllers
{
    public class RetentionPolicyController : Controller
    {
        private readonly InfluxClient _client;

        public RetentionPolicyController(InfluxClient client)
        {
            _client = client;
        }

        [HttpGet("{server}/{database}/rp/create")]
        public ActionResult New(string server, string database)
        {
            var vm = new NewRetentionPolicyViewModel
            {
                Server = server,
                Database = database
            };
            return View(vm);
        }

        [HttpPost("{server}/{database}/rp/create")]
        public async Task<ActionResult> Post(string server, string database,
            [FromForm] NewRetentionPolicyViewModel model)
        {
            var success = await _client.RetentionPolicies.Create(server, database, new RetentionPolicy
            {
                Name = model.Name,
                Duration = model.Duration,
                ShardGroupDuration = model.ShardDuration,
                Default = model.MakeDefault
            });

            return success
                ? RedirectToAction("Get", "Databases", new {server, name = database})
                : RedirectToAction("New", new {server, database});
        }
    }
}

src/AdmInflux/Views/Databases/Get.cshtml
@using AdmInflux.Client
@model AdmInflux.Models.DatabaseViewModel

@{
    ViewBag.Title = $"Database: {Model.Name}";
}

<div class="row">
    <div class="col-12">
        <h3>@Model.Name</h3>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4>Retention Policies</h4>
            </div>
            <div class="card-body">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Duration</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var retentionPolicy in Model.RetentionPolicies)
                    {
                        <tr>
                            <td>@retentionPolicy.Name @(retentionPolicy.Default ? "(default)" : "")</td>
                            <td>@(Durations.TryParse(retentionPolicy.Duration, out var ts) ? ts.ToDurationString() : retentionPolicy.Duration)</td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                <a class="btn btn-sm btn-success" asp-controller="RetentionPolicy" asp-action="New" asp-route-server="@Model.Server" asp-route-database="@Model.Name">New Retention Policy...</a>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4>Measurements</h4>
            </div>
            <div class="card-body">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Series</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var measurement in Model.Measurements)
                    {
                        <tr>
                            <td>@measurement.Measurement</td>
                            <td>@measurement.Count</td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>